import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="flex flex-col bg-white dark:bg-black dark:text-white font-serif">
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
